#!/bin/bash

SRC="/opt/battery-threshold/charge-control-end-threshold"
DST="/sys/class/power_supply/BAT0/charge_control_end_threshold"
show-threshold() {
  if [[ "$(cat $SRC)" == "$(cat $DST)" ]]; then
    cat $DST
  else
    set-threshold $SRC
    cat $DST
  fi
}

set-threshold() {
  # ! Braces are not supported...
  local re='^[0-9]{1,3}$'

  if [[ "$1" =~ $re ]]; then
    echo "$1" > $SRC  
  else
    >&2 echo "Invalid option '$1'. Expected a number from 1 ot 100"
  fi
}

if [[ -z "$1" ]]; then
  show-threshold
else
  set-threshold "$1"
fi
